export const ROUTES = {
  root: "/",
  home: "/home",
  hubPublic: "/hub/:slug",
  masterGroupPublic: "/mg/:id",
  maintenance: "/maintenance",
  termos: "/termos-de-uso",
  privacidade: "/privacidade",
  auth: {
    login: "/auth/login",
    cadastro: "/auth/cadastro",
    esqueciSenha: "/auth/esqueci-senha",
    resetarSenha: "/auth/resetar-senha",
    verificacaoEmail: "/auth/verificacao-email",
  },
  app: {
    dashboard: "/dashboard",
    connectionsRoot: "/connections",
    connectionsWhatsAppLegacy: "/connections/whatsapp",
    whatsappRoot: "/whatsapp",
    connectionsWhatsApp: "/whatsapp/configuracoes",
    telegramRoot: "/telegram",
    connectionsTelegramLegacy: "/connections/telegram",
    telegramConfiguracoes: "/telegram/configuracoes",
    connectionsMasterGroups: "/connections/master-groups",
    routes: "/routes",
    shopeeRoot: "/shopee",
    shopeeVitrine: "/shopee/vitrine",
    shopeePesquisa: "/shopee/pesquisa",
    shopeeConversor: "/conversor",
    shopeeAutomacoes: "/shopee/automacoes",
    shopeeTemplates: "/shopee/templates",
    shopeeConfiguracoes: "/shopee/configuracoes",
    mercadolivreRoot: "/meli",
    mercadolivreConfiguracoes: "/meli/configuracoes",
    vitrineMl: "/meli/vitrine",
    automacoesMeli: "/meli/automacoes",
    templatesMeli: "/meli/templates",
    amazonRoot: "/amazon",
    amazonConfiguracoes: "/amazon/configuracoes",
    vitrineAmazon: "/amazon/vitrine",
    conversorAmazon: "/amazon/conversor",
    automacoesamazon: "/amazon/automacoes",
    templatesAmazon: "/amazon/templates",
    schedules: "/schedules",
    modelosMensagem: "/modelos",
    linkHub: "/link-hub",
    history: "/history",
    account: "/account",
    ajuda: "/ajuda",
    afiliado: "/afiliado",
    metricasLegacy: "/metricas",
    metricas: "/whatsapp/metricas",
  },
  admin: {
    root: "/admin",
    users: "/admin/users",
    plans: "/admin/plans",
    access: "/admin/access",
    logs: "/admin/logs",
    notifications: "/admin/notifications",
    whatsapp: "/admin/whatsapp",
    mensagens: "/admin/mensagens",
    kiwify: "/admin/kiwify",
  },
} as const;

export const APP_ROUTE_TITLES: Record<string, string> = {
  [ROUTES.app.dashboard]: "Dashboard",
  [ROUTES.app.connectionsWhatsApp]: "Configurações WhatsApp",
  [ROUTES.app.telegramConfiguracoes]: "Telegram",
  [ROUTES.app.connectionsMasterGroups]: "Grupos mestres",
  [ROUTES.app.routes]: "Rotas automáticas",
  [ROUTES.app.shopeeVitrine]: "Vitrine de ofertas",
  [ROUTES.app.shopeePesquisa]: "Pesquisa de ofertas",
  [ROUTES.app.shopeeConversor]: "Conversor de links",
  [ROUTES.app.shopeeAutomacoes]: "Piloto automático",
  [ROUTES.app.shopeeTemplates]: "Modelos de mensagem Shopee",
  [ROUTES.app.shopeeConfiguracoes]: "Configurações Shopee",
  [ROUTES.app.mercadolivreConfiguracoes]: "Configurações Mercado Livre",
  [ROUTES.app.vitrineMl]: "Vitrine ML",
  [ROUTES.app.automacoesMeli]: "Piloto automático ML",
  [ROUTES.app.templatesMeli]: "Modelos de mensagem Mercado Livre",
  [ROUTES.app.amazonConfiguracoes]: "Configurações Amazon",
  [ROUTES.app.conversorAmazon]: "Conversor de links",
  [ROUTES.app.vitrineAmazon]: "Vitrine Amazon",
  [ROUTES.app.automacoesamazon]: "Piloto automático Amazon",
  [ROUTES.app.templatesAmazon]: "Modelos de mensagem Amazon",
  [ROUTES.app.schedules]: "Agendamentos",
  [ROUTES.app.modelosMensagem]: "Modelos de mensagem",
  [ROUTES.app.linkHub]: "Link Hub",
  [ROUTES.app.history]: "Histórico",
  [ROUTES.app.account]: "Minha conta",
  [ROUTES.app.ajuda]: "Ajuda",
  [ROUTES.app.afiliado]: "Parceiros",
  [ROUTES.app.metricas]: "Métricas WhatsApp",
};
