export const ROUTES = {
  root: "/",
  home: "/home",
  hubPublic: "/hub/:slug",
  maintenance: "/maintenance",
  termos: "/termos-de-uso",
  privacidade: "/privacidade",
  auth: {
    login: "/auth/login",
    cadastro: "/auth/cadastro",
    esqueciSenha: "/auth/esqueci-senha",
    resetarSenha: "/auth/resetar-senha",
    verificacaoEmail: "/auth/verificacao-email",
  },
  app: {
    dashboard: "/dashboard",
    connectionsRoot: "/connections",
    connectionsWhatsApp: "/connections/whatsapp",
    connectionsTelegram: "/connections/telegram",
    routes: "/routes",
    shopeeRoot: "/shopee",
    shopeeVitrine: "/shopee/vitrine",
    shopeePesquisa: "/shopee/pesquisa",
    shopeeConversor: "/conversor",
    shopeeAutomacoes: "/shopee/automacoes",
    shopeeTemplates: "/shopee/templates",
    shopeeConfiguracoes: "/shopee/configuracoes",
    mercadolivreRoot: "/mercadolivre",
    mercadolivreConfiguracoes: "/mercadolivre/configuracoes",
    vitrineMl: "/vitrineml",
    schedules: "/schedules",
    linkHub: "/link-hub",
    history: "/history",
    account: "/account",
  },
  admin: {
    root: "/admin",
    users: "/admin/users",
    plans: "/admin/plans",
    access: "/admin/access",
    logs: "/admin/logs",
    notifications: "/admin/notifications",
  },
} as const;

export const APP_ROUTE_TITLES: Record<string, string> = {
  [ROUTES.app.dashboard]: "Dashboard",
  [ROUTES.app.connectionsWhatsApp]: "WhatsApp",
  [ROUTES.app.connectionsTelegram]: "Telegram",
  [ROUTES.app.routes]: "Rotas Automáticas",
  [ROUTES.app.shopeeVitrine]: "Vitrine de ofertas",
  [ROUTES.app.shopeePesquisa]: "Pesquisa de ofertas",
  [ROUTES.app.shopeeConversor]: "Conversor de Links",
  [ROUTES.app.shopeeAutomacoes]: "Piloto automático",
  [ROUTES.app.shopeeTemplates]: "Templates Shopee",
  [ROUTES.app.shopeeConfiguracoes]: "Configurações Shopee",
  [ROUTES.app.mercadolivreConfiguracoes]: "Configurações Mercado Livre",
  [ROUTES.app.vitrineMl]: "Vitrine ML",
  [ROUTES.app.schedules]: "Agendamentos",
  [ROUTES.app.linkHub]: "Link Hub",
  [ROUTES.app.history]: "Histórico",
  [ROUTES.app.account]: "Minha Conta",
};
